
Running tests...
----------------------------------------------------------------------
...........................E......
======================================================================
ERROR [0.006s]: test_send_product_nodes_tests (test_send_product_tests.SendProductTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/Users/sarahhoover/PycharmProjects/G01.2023.T04.EG3/src/unittest/python/test_send_product_tests.py", line 67, in test_send_product_nodes_tests
    for filename in os.listdir(directory):
FileNotFoundError: [Errno 2] No such file or directory: 'send_product_tests/json_decode_error'

----------------------------------------------------------------------
Ran 34 tests in 0.470s

FAILED (errors=1)

Generating XML reports...
